### ISSUE TITLE
Receiver binding

### ISSUE THREAD

**Issue by enthru** [jancona/hpsdrconnector#12]
Hello! Is it possible to choose to which receiver bind selected band (hpsdr device in owrx)?

**Comment by jancona** [comment]
I don't understand the question. Could you explain what you're doing, what happens now and what you'd like to happen? Thanks!

**Comment by enthru** [comment]
Yeah, sorry for unclear explanation. 
For example: I have device with two antennas connected. One antenna for 20m band and second for 40m band. When you open 20m device in OWRX it shows good reception of 20m band, but... if you switch to the 40m band it will open the same logical receiver with 20m antenna connected to play 40m band.
To avoid this you need to keep 20m band opened from another laptop or from additional tab in browser and OWRX will able to create 2d receiver with 40m antenna connected.
Looks like with one listener it always opens first receiver for any band which is bad for multi antenna setup because it can choose wrong antenna for band.

**Comment by jancona** [comment]
Can you go into more detail on your setup? How many physical devices, of what type (Hermes Lite 2, Red Pitaya, something else)? Where are the antennas connected?

**Comment by enthru** [comment]
Sure. 
One physical device - redpitaya clone trx-duo (with Pavel Demin software) 
Antennas connected to the input one and two. 
I can share a link to my OWRX instance if it helps

**Comment by luarvique** [comment]
I think the idea is that at least for some devices, formally compatible with the Hermes protocol, not all slices are physically the same (as in, they may actually correspond to different SDR units within the device). Hence, there has to be a way to request a specific slice, by ID.

Did I get it right?

**Comment by enthru** [comment]
I'm not sure what does mean slices (sorry not so familiar with openwebrx internals), but looks like you are right. In my case it's different ADCs in the device connected to different antennas. So somehow I need to "hardcode" only specific ADC/Antenna to the specific band (or multiple bands if antenna is wideband, but for only strict selected bands).

**Comment by jancona** [comment]
Unfortunately, I don't have a Red Pitaya. In order to do this I need either documentation that specifies how to communicate which antenna to use, or an example of software that already does what you want. I've looked at https://pavel-demin.github.io/red-pitaya-notes/, but I don't see any documentation of what he may have added to the protocol. I don't see anything in his source code either, although I haven't studied it in depth. I suggest you ask Pavel if his software does what you want, and if it does, what bits in the protocol are used to do the selection.

I'm going to close this issue, but if you come up with more information, please feel free to reopen it.

**Comment by enthru** [comment]
Okay, thanks. I will try to learn more about hpsdr protocol and openwebrx to find the ways how to fix this, if I able.
